### ISSUE TITLE
Update README.md, still references 

### ISSUE THREAD

**Issue by lhridley** [shaal/ddev-gitpod#107]
Under heading [How does it work?](https://github.com/shaal/ddev-gitpod#how-does-it-work), list item 2, you still have a reference to ".ddev/gitpod-setup-ddev.sh", which was removed from the repository in [this commit](https://github.com/shaal/ddev-gitpod/commit/a9785652f08488066ee32c130c4e3c451159be46).

Please revise the README.md

**Comment by rfay** [comment]
@lhridley It would have been easier to just visit https://github.com/shaal/ddev-gitpod/blob/main/README.md and click the edit button :)
<img width="462" alt="ddev-gitpod_README_md_at_main_·_shaal_ddev-gitpod" src="https://user-images.githubusercontent.com/112444/147680595-7e132cf3-0996-4283-a37b-02046a17fab8.png">

**Comment by lhridley** [comment]
@rfay perhaps.  However, as a new user of this project, I'm not going to assume that this was intentional, so I'll leave that decision to the project maintainer.  It may very well have been an oversight on his part.

**Comment by shaal** [comment]
@lhridley Thank you.
Thanks to numerous updates in ddev, running it in Gitpod became much simpler.

I updated the README file, please let me know what you think.
