### ISSUE TITLE
ddev-gitpod should not expose all ports equally

### ISSUE THREAD

**Issue by rfay** [shaal/ddev-gitpod#33]
When you start up a project with ddev-gitpod, you get a bunch of ports exposed, and additional_fqdns for each of them. And of course they're not all equal. Some of for PHPMyAdmin or mailhog, which are rarely used. but they're all there in the startup string equally, for example:

> Project can be reached at https://ddev-gitpod.ddev.site:8443 https://8025-chocolate-donkey-ypicpjv8.ws-us03.gitpod.io:8443 https://8036-chocolate-donkey-ypicpjv8.ws-us03.gitpod.io:8443 https://8080-chocolate-donkey-ypicpjv8.ws-us03.gitpod.io:8443 https://127.0.0.1:32771 

You see there that the *useful* URL is the next-to-last one, https://8080-chocolate-donkey-ypicpjv8.ws-us03.gitpod.io:8443

I think probably we'll have to add some gitpod functionality to ddev itself to work around this. It may be that since (all?) the router features of ddev-router are being done by gitpod's termination that we should just not use ddev-router in the context of gitpod.

**Comment by shaal** [comment]
Thank you go that.
Why is https://127.0.0.1:32771 not showing anything in gitpod?

**Comment by rfay** [comment]
Well, it can't work from a browser obviously. Because that's only good on the machine where it's exposed. And it's different every time a project starts.

**Comment by shaal** [comment]
Right
I meant when you click on that link while in gitpod, it converts that link
for you correctly, but opening the correct link (32771-pink-chocolate-...)
Does not display what we're expecting.

**Comment by rfay** [comment]
I don't know why it doesn't seem to work; works fine locally.

**Comment by shaal** [comment]
@rfay should we close this?

**Comment by rfay** [comment]
If you're happy I'm happy.

**Comment by rfay** [comment]
But is there a reason to continue to maintain ddev-gitpod?

**Comment by shaal** [comment]
Yeah.
It's a simple example of default Drupal project (Umami on latest Drupal) + ddev + Gitpod.
