### ISSUE TITLE
Add some tags for GitHub search

### ISSUE THREAD

**Issue by theodorosploumis** [shaal/ddev-gitpod#5]
Please, add some tags and topics for GitHub search to make this project available on GitHub search.
Some keywords like DDEV, gitpod, Drupal etc would really help it. 
Thank you for the video also!

**Comment by shaal** [comment]
Thank you for the great suggestion!
I added some tags, and added the video demo in the Readme.

Please let me know what else can we improve.

**Comment by shaal** [comment]
Feel free to open this issue if you have additional ideas.
