### ISSUE TITLE
"no space left on device"

### ISSUE THREAD

**Issue by ultimike** [shaal/ddev-gitpod#80]
I used this repo to spin up a fresh Drupal 9 site on Gitpod, and it worked fine for a little bit, but then I received the following error while trying to rebuild caches:

> $ ddev drush cr
> Adding custom commands failed: mkdir /workspace/ddev-gitpod/.ddev/.global_commands: no space left on device

While searching this project's issue queue and poking around a few other places, I didn't run any additional commands in the Gitpod terminal for 5-10 minutes. Then, on a whim, I retried the same command and it worked. I then rebuilt caches a few times, installed a module using Composer, then enabled it using Drush, followed by loading a bunch of pages in the browser - all with no issues.

It appears that the "no space left on device" error was temporary, but I have no idea why. Could it be that Gitpod autoresizes things on-the-fly?

-mike

**Comment by shaal** [comment]
I heard from other people about this kind of error before.
@rfay you encountered it as well, right?

A Gitpod workspace should have 30gb storage space (which is plenty for `ddev-gitpod`).
It might be a bug with how Gitpod distribute workspaces and drives in the cloud?
Also, that the issue got itself resolved is interesting.

I would suggest the next time it happens -
* File a bug report with Gitpod - https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=bug&template=bug_report.yml
* Shutdown the workpsace, and reopen it again.

**Comment by rfay** [comment]
I imagine this is the same as https://github.com/gitpod-io/gitpod/issues/4902 - and filing an issue each time will help them know the scope of the problem. Or following one up, not sure.

**Comment by shaal** [comment]
This seems to be a rare issue with Gitpod and it has been resolved.
If this happens again, I'll be happy to look into it.
