### ISSUE TITLE
Old DDEV version

### ISSUE THREAD

**Issue by tyler36** [shaal/ddev-gitpod#89]
I just spun this up and noticed that it's using an older version of DDEV.

```shell
gitpod /workspace/ddev-gitpod $ ddev --version
ddev version v1.17.7
```

I see that you pull in DDEV via brew in `/.gitpod.Dockerfile`
```Dockerfile
RUN brew update && brew install drud/ddev/ddev && mkcert -install
```

I tried updating DDEV via brew but it thinks it's the latest.
```shell
gitpod /workspace/ddev-gitpod $ brew upgrade ddev
Warning: drud/ddev/ddev 1.17.7 already installed
```

DDEV 1.18.0 was release on the 2021-09-28 (24 days ago) so something is not getting updated. Any thoughts?

**Comment by shaal** [comment]
Thank you @tyler36

I ran Gitpod's image build, which got `ddev` upgraded to its latest version 1.18.

There are some improvements that were already made in DrupalPod and didn't make it yet to ddev-gitpod repo.

**Comment by tyler36** [comment]
Thank you for the update. 

Just tried it but am still getting the old version.

```
gitpod /workspace/ddev-gitpod $ ddev --version
ddev version v1.17.7
```

I assume it might take time to `sync` so will try again in a couple of hours.
